# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6789e0a012420c4a9db63973ab75dcdc1d59629fc13dfb67b45566363b019b19057ff0f1ab1727b96ceb26e2be65feb4c938935c6316591f7dfa82b3dcd75c

test:
  secret_key_base: fa8d68ff03daf50717d91fdc96955fbc72875d7159d8f9a5c03ac455d558ec237592b790ac35febd322f0c101a3c333191404cc0899c1cc2de61e52b95f36707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
